#! /usr/local/bin/zsh

user_path="/Users/mac-gaogao/"

declare -a dot_files
dot_files=(
  ".gitconfig"
  ".tmux.conf"
  ".vimrc"
  ".zshrc"
)

for dot_file in $dot_files
do
  full_path=$user_path$dot_file
  if [ -e $full_path ]
  then
    rm $dot_file
    echo "remove ${dot_file}"
    cp $full_path $dot_file
    echo "copy ${full_path} to ${dot_file}"
  else
    echo "${full_path} isn't exist"
  fi
done
